[en]
    label  = "English"
    title  = "Hugo Theme Stack"
    weight = 1

    [en.params.sidebar]
        subtitle = "Card-style Hugo theme designed for bloggers"

[zh]
    label  = "简体中文"
    title  = "Wuwei1"
    weight = 2

    [zh.params.sidebar]
        subtitle = "学习中"

[ja]
    label  = "日本語"
    title  = "Hugo Theme Stack"
    weight = 4

    [ja.params.sidebar]
        subtitle = "ブログ用のカードスタイルの Hugo テーマ"
